baseURL = 'http://blog.iamqh.me'
languageCode = 'vi-vn'
theme = 'PaperMod'
title = "iamqh's Blog"

[params]
DateFormat = "January 2, 2006"
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowPostNavLinks = true
ShowReadingTime = true
ShowShareButtons = true
author = "iamqh"
comments = true
defaultTheme = "auto"
disableScrollToTop = false
disableSpecial1stPost = false
disableThemeToggle = false
env = 'development'
hideSummary = false
hidemeta = false
math = true
showtoc = true
title = "iamqh's Blog"
tocopen = true
[params.label]
icon = "/logo.png"

[params.homeInfoParams]
Content = """Write code, love life!
<br/><br/>
  Look like you've found my tiny space on the Internet.
<br/><br/>
  Beside some posts I've wrote here, you can find my notes in [<b style="font-size:15pt;">Everyday Learning</b>](/everyday)
  
  which writing about what I learned "everyday" üòÅ. 
  """
Title = "Hi there! I'm Hoa üëã"

[[params.socialIcons]]
name = "facebook"
url = "https://facebook.com/phamquang.hoa.79"

[[params.socialIcons]]
name = "linkedin"
url = "https://stackoverflow.com"

[[params.socialIcons]]
name = "github"
url = "https://github.com/HoaPham98"

[[params.socialIcons]]
name = "email"
url = "mailto:hoapq.4398@gmail.com"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"

[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "everyday"
name = "Everyday"
url = "/everyday/"
weight = 6
[[menu.main]]
name = "Archive"
identifier = "archives"
url = "/archives/"
weight = 5

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true
